name: Build and Push
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (x.y.z)
        required: true
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: v1

      - name: Merge from master
        run: |
          git fetch
          git merge origin/master

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Push
        run: |
          git config --global user.name "Wavle Developer"
          git config --global user.email "wavle-developer@users.noreply.github.com"
          git add --force dist
          yarn version --new-version "${{ github.event.inputs.version }}"
          git checkout -b master origin/master
          git merge v1
          git push --all
