name: Test on MacOS
on:
  workflow_dispatch:

jobs:
  basic-test:
    name: Basic Testing
    runs-on: macos-latest
    steps:
      - name: Create dummy file
        run: |
          echo "dummy" > dummy.txt

      - uses: yumis-coconudge/clean-workspace-action@v1.0.6

      - name: Check files
        run: |
          ls -1
          if [ "$(ls -1 | wc -l)" -gt "0" ]; then
            echo "Clean workspace failed"
            exit 1
          fi

  additional-path-directory-test:
    name: Additional Path(Directory) Testing
    runs-on: macos-latest
    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1.0.6

      - uses: actions/checkout@v4.1.1

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - uses: yumis-coconudge/clean-workspace-action@v1.0.6
        with:
          additional-path: "${{ steps.yarn-cache-dir-path.outputs.dir }}"

      - name: Check files
        run: |
          ls -a1
          if [ "$(ls -a1 | wc -l)" -gt "2" ]; then
            echo "Clean workspace failed"
            exit 1
          fi
          ls -a1 ${{ steps.yarn-cache-dir-path.outputs.dir }}
          if [ "$(ls -a1 ${{ steps.yarn-cache-dir-path.outputs.dir }} | wc -l)" -gt "2" ]; then
            echo "Clean additional path failed"
            exit 1
          fi

  additional-path-multiple-files-test:
    name: Additional Path(Multiple Files) Testing
    runs-on: macos-latest
    steps:
      - name: Create dummy files
        run: |
          cd ~
          mkdir test
          cd test
          echo "dummy" > a.txt
          echo "dummy" > b.txt

      - uses: yumis-coconudge/clean-workspace-action@v1.0.6
        with:
          additional-path: "~/test/a.txt,~/test/b.txt"

      - name: Check files
        run: |
          ls -1 ~/test
          if [ "$(ls -1 ~/test | wc -l)" -gt "0" ]; then
            echo "Clean additional path failed"
            exit 1
          fi
